


export const FETCH_PRODUCTS_REQUEST = 'FECTH_PRODUXTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';


export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';